<?php if (isset($this->pageCount) && $this->pageCount > 1): ?>
    <nav>
        <ul>
            <!-- Previous page link -->
            <?php if (isset($this->previous) && ! empty($this->previous)): ?>
                <li>
                    <a>&Larr;</a>
                </li>
            <?php endif ?>

            <!-- Numbered page links -->
            <?php foreach (range(1, $this->pageCount) as $page): ?>
                <?php if ($page === $current): ?>
                    <li>
                        <a><?= $this->escapeHtml($page) ?></a>
                    </li>
                <?php else: ?>
                    <li>
                        <span><?= $this->escapeHtml($page) ?></span>
                    </li>
                <?php endif ?>
            <?php endforeach ?>

            <!-- Next page link -->
            <?php if (isset($this->next) && ! empty($this->next)): ?>
                <li>
                    <a>&Rarr;</a>
                </li>
            <?php endif ?>
        </ul>
    </nav>
<?php endif ?>