<?php if (isset($pageCount) && $pageCount > 1): ?>
    <nav id="navigation">
        <ul>
            <!-- Previous page link -->
            <?php if (isset($previous) && ! empty($previous)): ?>
                <li id="prev">
                    <a href="/blog/<?= $this->e($previous) ?>">&Larr;</a>
                </li>
            <?php endif ?>

            <!-- Numbered page links -->
            <?php foreach (range(1, $pageCount) as $page): ?>
                <?php if ($page === $current): ?>
                    <li id="page-<?= $this->e($page) ?>">
                        <a><?= $this->e($page) ?></a>
                    </li>
                <?php else: ?>
                    <li id="current-page">
                        <span><?= $this->e($page) ?></span>
                    </li>
                <?php endif ?>
            <?php endforeach ?>

            <!-- Next page link -->
            <?php if (isset($next) && ! empty($next)): ?>
                <li id="next">
                    <a href="/blog/<?= $this->e($next) ?>">&Rarr;</a>
                </li>
            <?php endif ?>
        </ul>
    </nav>
<?php endif ?>